# Generated by Django 4.2.4 on 2023-08-21 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chose_dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.CharField(max_length=150)),
                ('dest_description', models.CharField(max_length=3000)),
                ('init_date_at_dest', models.DateField(verbose_name='Starting date at destination')),
                ('end_date_at_dest', models.DateField(verbose_name='Ending date at destination')),
                ('comments', models.TextField(max_length=3000)),
            ],
            options={
                'ordering': ['-init_date_at_dest'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.CharField(max_length=150)),
                ('dest_description', models.TextField(max_length=3000)),
                ('dest_address', models.CharField(max_length=300)),
                ('dest_country', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_travel_date', models.DateField(verbose_name='Starting journey date')),
                ('end_travel_date', models.DateField(verbose_name='Ending journey date')),
                ('user_budget', models.IntegerField()),
                ('itin_description', models.TextField(max_length=3000)),
                ('chose_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itin_for', to='main_app.chose_dest')),
                ('destinations', models.ManyToManyField(to='main_app.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('era_name', models.CharField(max_length=250)),
                ('era_peroid', models.CharField(max_length=200)),
                ('era_description', models.TextField(max_length=2000)),
                ('destinations', models.ManyToManyField(to='main_app.destination')),
            ],
        ),
        migrations.AddField(
            model_name='chose_dest',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_destin', to='main_app.itinerary'),
        ),
    ]
