# Generated by Django 4.2.4 on 2023-08-20 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosDest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destName', models.CharField(max_length=150)),
                ('destDescription', models.CharField(max_length=500)),
                ('dateAtDest', models.DateField()),
                ('comments', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destName', models.CharField(max_length=150)),
                ('destDescription', models.CharField(max_length=500)),
                ('destAddress', models.CharField(max_length=300)),
                ('destCountry', models.CharField(max_length=20)),
                ('priceRange', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTravel', models.DateTimeField(verbose_name='Travel Date')),
                ('description', models.TextField(max_length=500)),
                ('chosDest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_for', to='main_app.chosdest')),
                ('destinations', models.ManyToManyField(to='main_app.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eraName', models.CharField(max_length=250)),
                ('eraPeroid', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('destinations', models.ManyToManyField(to='main_app.destination')),
            ],
        ),
        migrations.AddField(
            model_name='chosdest',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chos_destinations', to='main_app.itinerary'),
        ),
    ]
