# Generated by Django 4.2.4 on 2023-08-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='era',
            old_name='destination',
            new_name='destinations',
        ),
        migrations.RenameField(
            model_name='era',
            old_name='era_peroid',
            new_name='era_period',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='init_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='end_travel_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='init_travel_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='itin_description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user_budget',
            field=models.IntegerField(verbose_name='Budget'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='end_date_at_dest',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='init_date_at_dest',
            field=models.DateField(),
        ),
    ]
