# Generated by Django 4.2.4 on 2023-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_destination_era_destinations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='dest_latitude',
            field=models.IntegerField(default=1, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='dest_longitude',
            field=models.IntegerField(default=1, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_address',
            field=models.CharField(max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_description',
            field=models.TextField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price_range',
            field=models.CharField(max_length=100, verbose_name='Price Range'),
        ),
        migrations.AlterField(
            model_name='era',
            name='era_description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='era',
            name='era_name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='era',
            name='era_period',
            field=models.CharField(max_length=200, verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='comments',
            field=models.TextField(max_length=3000, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='dest_description',
            field=models.CharField(max_length=3000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='dest_name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='end_date_at_dest',
            field=models.DateTimeField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='init_date_at_dest',
            field=models.DateTimeField(verbose_name='Start'),
        ),
    ]
