# Generated by Django 4.2.4 on 2023-08-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_destination_dest_latitude_destination_dest_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='dest_latitude',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='dest_longitude',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Longitude'),
        ),
    ]
